# To run the end to end devsecops pipeline.

name: DevSecOps
on: 
    push:
        branches: main


jobs:

    #code stage with shift left. Before build and deploy shift felt to check the code using secury scan. 
    code-quality:
        uses: ./.github/workflows/code-quality.yml
