# My goal i to save and protect the credential

name: Secrets Scanning
on:
    workflow_call

jobs: 
    scan-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v7
              with:
                fetch-depth: 0

            - name: Git leak scanner
              uses: gitleaks/gitleaks-action@v3
              env:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}